Bump MSRV to 1.65
regex 1.10.0 requires it.

```
error: package `regex v1.10.0` cannot be built because it requires rustc 1.65 or newer, while the currently active rustc version is 1.63.0
```