ci: Temporarily disable -Zmiri-symbolic-alignment-check due to memchr 2.6.0 bug
```
error: Undefined Behavior: accessing memory with alignment 1, but alignment 16 is required
    --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/x86/sse2.rs:1188:5
     |
1188 |     *mem_addr
     |     ^^^^^^^^^ accessing memory with alignment 1, but alignment 16 is required
     |
     = help: this usually indicates that your program performed an invalid operation and caused Undefined Behavior
     = help: but due to `-Zmiri-symbolic-alignment-check`, alignment errors can also be false positives
     = note: BACKTRACE:
     = note: inside `std::arch::x86_64::_mm_load_si128` at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/x86/sse2.rs:1188:5: 1188:14
     = note: inside `memchr::vector::x86sse2::<impl memchr::vector::Vector for std::arch::x86_64::__m128i>::load_aligned` at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memchr-2.6.0/src/vector.rs:216:13: 216:51
     = note: inside `memchr::arch::generic::memchr::One::<std::arch::x86_64::__m128i>::find_raw` at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memchr-2.6.0/src/arch/generic/memchr.rs:175:25: 175:45
     = note: inside `memchr::arch::x86_64::sse2::memchr::One::find_raw_impl` at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memchr-2.6.0/src/arch/x86_64/sse2/memchr.rs:290:9: 290:36
     = note: inside `memchr::arch::x86_64::sse2::memchr::One::find_raw` at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memchr-2.6.0/src/arch/x86_64/sse2/memchr.rs:185:9: 185:39
     = note: inside `memchr::arch::x86_64::memchr::memchr_raw::find_sse2` at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memchr-2.6.0/src/arch/x86_64/memchr.rs:96:13: 97:51
     = note: inside `memchr::arch::x86_64::memchr::memchr_raw` at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memchr-2.6.0/src/arch/x86_64/memchr.rs:153:13: 157:14
     = note: inside `memchr::memchr::memchr_raw` at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memchr-2.6.0/src/memchr.rs:515:9: 515:68
     = note: inside closure at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memchr-2.6.0/src/memchr.rs:322:33: 322:63
     = note: inside `memchr::arch::generic::memchr::Iter::<'_>::next::<[closure@<memchr::memchr::Memchr<'_> as std::iter::Iterator>::next::{closure#0}]>` at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memchr-2.6.0/src/arch/generic/memchr.rs:1046:21: 1046:51
     = note: inside `<memchr::memchr::Memchr<'_> as std::iter::Iterator>::next` at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memchr-2.6.0/src/memchr.rs:322:13: 322:64
note: inside `<parse_changelog::Lines<'_> as std::iter::Iterator>::next`
    --> /home/runner/work/parse-changelog/parse-changelog/src/lib.rs:686:38
     |
686  |         let (line, line_end) = match self.iter.next() {
     |                                      ^^^^^^^^^^^^^^^^
note: inside `parse_changelog::Lines::<'_>::peek2`
    --> /home/runner/work/parse-changelog/parse-changelog/src/lib.rs:669:23
     |
669  |         let peeked2 = self.next();
     |                       ^^^^^^^^^^^
note: inside `parse_changelog::heading`
    --> /home/runner/work/parse-changelog/parse-changelog/src/lib.rs:727:31
     |
727  |     if let Some((next, ..)) = lines.peek2() {
     |                               ^^^^^^^^^^^^^
note: inside `<parse_changelog::ParseIter<'_, '_> as std::iter::Iterator>::next`
    --> /home/runner/work/parse-changelog/parse-changelog/src/lib.rs:546:64
     |
546  |                 if on_code_block || on_comment { None } else { heading(line, &mut self.lines) };
     |                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `parse_changelog::Parser::parse`
    --> /home/runner/work/parse-changelog/parse-changelog/src/lib.rs:423:24
     |
423  |         for release in self.parse_iter(text) {
     |                        ^^^^^^^^^^^^^^^^^^^^^
note: inside `parse_changelog::parse`
    --> /home/runner/work/parse-changelog/parse-changelog/src/lib.rs:247:5
     |
247  |     Parser::new().parse(text)
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `comment`
    --> tests/test.rs:218:21
     |
218  |     let changelog = parse(changelog).unwrap();
     |                     ^^^^^^^^^^^^^^^^
note: inside closure
    --> tests/test.rs:178:14
     |
177  | #[test]
     | ------- in this procedural macro expansion
178  | fn comment() {
     |              ^
     = note: this error originates in the attribute macro `test` (in Nightly builds, run with -Z macro-backtrace for more info)

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace
```