memchr::Memchr is no longer thread-safe since memchr 2.6.0
```
error[E0277]: `*const u8` cannot be sent between threads safely
   --> src/gen/assert_impl.rs:38:19
    |
38  |     assert_send::<crate::ParseIter<'_, '_>>();
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^ `*const u8` cannot be sent between threads safely
    |
    = help: within `ParseIter<'_, '_>`, the trait `Send` is not implemented for `*const u8`
    = note: consider using `std::sync::Arc<*const u8>`; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>
note: required because it appears within the type `Iter<'_>`
   --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memchr-2.6.0/src/arch/generic/memchr.rs:999:19
    |
999 | pub(crate) struct Iter<'h> {
    |                   ^^^^
note: required because it appears within the type `Memchr<'_>`
   --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memchr-2.6.0/src/memchr.rs:288:12
    |
288 | pub struct Memchr<'h> {
    |            ^^^^^^
note: required because it appears within the type `Lines<'_>`
   --> src/lib.rs:643:8
    |
643 | struct Lines<'a> {
    |        ^^^^^
note: required because it appears within the type `ParseIter<'_, '_>`
   --> src/lib.rs:456:12
    |
456 | pub struct ParseIter<'a, 'r> {
    |            ^^^^^^^^^
note: required by a bound in `assert_send`
   --> src/gen/assert_impl.rs:8:28
    |
8   | fn assert_send<T: ?Sized + Send>() {}
    |                            ^^^^ required by this bound in `assert_send`

error[E0277]: `*const u8` cannot be shared between threads safely
   --> src/gen/assert_impl.rs:39:19
    |
39  |     assert_sync::<crate::ParseIter<'_, '_>>();
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^ `*const u8` cannot be shared between threads safely
    |
    = help: within `ParseIter<'_, '_>`, the trait `Sync` is not implemented for `*const u8`
    = note: consider using `std::sync::Arc<*const u8>`; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>
note: required because it appears within the type `Iter<'_>`
   --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memchr-2.6.0/src/arch/generic/memchr.rs:999:19
    |
999 | pub(crate) struct Iter<'h> {
    |                   ^^^^
note: required because it appears within the type `Memchr<'_>`
   --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memchr-2.6.0/src/memchr.rs:288:12
    |
288 | pub struct Memchr<'h> {
    |            ^^^^^^
note: required because it appears within the type `Lines<'_>`
   --> src/lib.rs:643:8
    |
643 | struct Lines<'a> {
    |        ^^^^^
note: required because it appears within the type `ParseIter<'_, '_>`
   --> src/lib.rs:456:12
    |
456 | pub struct ParseIter<'a, 'r> {
    |            ^^^^^^^^^
note: required by a bound in `assert_sync`
   --> src/gen/assert_impl.rs:10:28
    |
10  | fn assert_sync<T: ?Sized + Sync>() {}
    |                            ^^^^ required by this bound in `assert_sync`
```